CREATE TABLE IF NOT EXISTS person (
    id bigint NOT NULL AUTO_INCREMENT,
    nome varchar(255) DEFAULT NULL,
    cpf varchar(14) DEFAULT NULL,
    rg varchar(12) DEFAULT NULL,
    data_nasc timestamp,
    sexo varchar(9) DEFAULT NULL,
    mae varchar(255) DEFAULT NULL,
    pai varchar(255) DEFAULT NULL,
    email varchar(255) DEFAULT NULL,
    cep varchar(10) DEFAULT NULL,
    endereco varchar(255) DEFAULT NULL,
    numero int(3) DEFAULT NULL,
    bairro varchar(255) DEFAULT NULL,
    cidade varchar(255) DEFAULT NULL,
    estado varchar(2) DEFAULT NULL,
    telefone varchar(16) DEFAULT NULL,
    celular varchar(17) DEFAULT NULL,
    altura double DEFAULT NULL,
    peso double DEFAULT NULL,
    tipo_sanguineo varchar(2) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY UK_cpf (cpf),
    UNIQUE KEY UK_rg (rg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;